import os
import re

def extract_problem_info(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            match = re.search(r'//\s*Problem:\s*(https?://codeforces\.com/contest/\d+/problem/\w+)', line)
            if match:
                return match.group(1)
    return None

def update_readme():
    cpp_files = [f for f in os.listdir('.') if f.endswith('.cpp')]
    problems = []

    for file in cpp_files:
        link = extract_problem_info(file)
        if link:
            problem_name = file.replace('.cpp', '')
            problems.append((problem_name, link))

    problems.sort()

    with open("README.md", "w", encoding='utf-8') as f:
        f.write("# 🧠 Codeforces Problem Solutions\n\n")
        f.write("This repository contains my solutions to Codeforces problems with brief explanations.\n\n")
        f.write("## 📋 Solved Problems\n\n")

        for name, link in problems:
            f.write(f"- [{name}]({link})\n")

        f.write("\n---\n")
        f.write("📌 Auto-generated by `update_readme.py`\n")

    print(f"✅ README.md updated with {len(problems)} problems.")

if __name__ == "__main__":
    update_readme()
